#include "hardware.h"
#include "bcm2835/gpio.h"
#include "bcm2835/uart.h"
#include "bcm2835/power.h"
#include "bcm2835/pic.h"

static inline void kernel_hardware_led_init ( );

void kernel_hardware_init ( )
{
    // Make sure all peripherals are powered off
    power_init ( );

    // Make sure no FIQ or IRQ will be generated by the PIC
    pic_disable_all_interrupts ( );

    kernel_hardware_led_init ( );
    uart_init ( );

    printu ( "Welcome!" );
    printu ( "Hardware initialization complete" );
}

void kernel_hardware_led_init ( )
{
    kernel_gpio_configure ( GPIO_LED, GPIO_FSEL_OUTPUT );
    kernel_gpio_output_set ( GPIO_LED );
}
