#include "hardware.h"
#include "bcm2835/power.h"
#include "bcm2835/pic.h"
#include "bcm2835/uart.h"
#include "bcm2835/systimer.h"
#include "bcm2835/gpio.h"
#include "usb_core.h"
#include "pcb.h"

static inline void hardware_led_init ( );

void hardware_init ( )
{
    // Make sure all peripherals are powered off
    power_init ( );

    // Make sure no FIQ or IRQ will be generated by the PIC
    pic_disable_all_interrupts ( );

    uart_init ( );
    printu ( "Welcome!" );

    printu ( "Initializing Timer" );
    systimer_init ( );

    printu ( "Configuring OK_LED" );
    hardware_led_init ( );

    printu ( "Launching USB Core Init process" );
    pcb_create ( usb_init, 0 );

    printu ( "Hardware initialization complete" );
}

void hardware_led_init ( )
{
    gpio_configure ( GPIO_LED, GPIO_FSEL_OUTPUT );
    gpio_output_set ( GPIO_LED );
}
